### ISSUE TITLE
"Palm Tree"  CPT should be enabled via a Filter 

### ISSUE THREAD

**Issue by d4mation** [realbig/rbm-cpts#4]
I figure the Palm Tree CPT is there for Testing/as an Example. However, you have to remove it from the `$wp_post_types` Global Array and remove it from the menu manually for Production Environments. 

Maybe its inclusion should be wrapped in a Filter that is normally set to `__return_false` and can be set to `__return_true` when it is needed?

**Comment by joelworsham** [comment]
Aha yes. Well, that was placed as an example with the intent of re-purposing this plugin each time, rather than including it as a mu-plugin or something. I think the best course of action is to simply delete it. I think things are semantic enough to understand how to use it, plus we can create a wiki or something if we want.

**Comment by d4mation** [comment]
I think a Wiki is a great idea, actually. It would be a good place to keep documentation of any Actions/Filters as well as a place to house an example like the "Palm Tree".

**Comment by d4mation** [comment]
Added to Wiki.
